---
- name: Deploy SSH Keys to Debian Server
  hosts: debian_servers
  become: true
  gather_facts: true

  tasks:
    # ============================================
    # Ensure admin user exists
    # ============================================
    - name: Ensure admin user exists
      user:
        name: admin
        state: present

    # ============================================
    # Configure SSH directory
    # ============================================
    - name: Ensure .ssh directory exists for admin user
      file:
        path: /home/admin/.ssh
        state: directory
        owner: admin
        group: admin
        mode: '0700'

    # ============================================
    # Generate SSH key pair
    # ============================================
    - name: Generate RSA SSH key pair for admin user
      openssh_keypair:
        path: /home/admin/.ssh/id_rsa
        type: rsa
        size: 4096
        owner: admin
        group: admin
        comment: "admin@{{ ansible_hostname }}"
      register: ssh_keypair

    - name: Read generated public key
      slurp:
        src: /home/admin/.ssh/id_rsa.pub
      register: public_key_content

    - name: Display generated public key
      debug:
        msg: "{{ public_key_content.content | b64decode }}"
      when: ssh_keypair.changed

    # ============================================
    # Deploy SSH public keys
    # ============================================
    - name: Find all public keys in keys/ directory
      find:
        paths: "{{ playbook_dir }}/keys"
        patterns: "*.pub"
      register: public_keys
      delegate_to: localhost
      become: false

    - name: Deploy public keys to authorized_keys
      authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ public_keys.files }}"
      when: public_keys.files | length > 0
