---
- name: Deploy SSH Keys to Debian Server
  hosts: debian_servers
  become: yes
  gather_facts: yes

  tasks:
    # ============================================
    # Ensure debian user exists
    # ============================================
    - name: Ensure debian user exists
      user:
        name: debian
        state: present

    # ============================================
    # Configure SSH directory
    # ============================================
    - name: Ensure .ssh directory exists for debian user
      file:
        path: /home/debian/.ssh
        state: directory
        owner: debian
        group: debian
        mode: '0700'

    # ============================================
    # Generate SSH key pair
    # ============================================
    - name: Generate RSA SSH key pair for debian user
      openssh_keypair:
        path: /home/debian/.ssh/id_rsa
        type: rsa
        size: 4096
        owner: debian
        group: debian
        comment: "debian@{{ ansible_hostname }}"
      register: ssh_keypair

    - name: Read generated public key
      slurp:
        src: /home/debian/.ssh/id_rsa.pub
      register: public_key_content

    - name: Display generated public key
      debug:
        msg: "{{ public_key_content.content | b64decode }}"
      when: ssh_keypair.changed

    # ============================================
    # Deploy SSH public keys
    # ============================================
    - name: Find all public keys in keys/ directory
      find:
        paths: "{{ playbook_dir }}/keys"
        patterns: "*.pub"
      register: public_keys
      delegate_to: localhost
      become: no

    - name: Deploy public keys to authorized_keys
      authorized_key:
        user: debian
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ public_keys.files }}"
      when: public_keys.files | length > 0
