---
- name: Setup Ubuntu Server
  hosts: ubuntu_servers
  become: yes
  gather_facts: yes

  tasks:
    # ============================================
    # Create ubuntu user
    # ============================================
    - name: Create ubuntu user with home directory
      user:
        name: ubuntu
        state: present
        create_home: yes
        home: /home/ubuntu
        shell: /bin/bash
        groups: []

    # ============================================
    # Configure sudo access
    # ============================================
    - name: Configure passwordless sudo for ubuntu user
      copy:
        content: "ubuntu ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/ubuntu
        mode: '0440'
        validate: 'visudo -cf %s'

    # ============================================
    # Deploy SSH public keys
    # ============================================
    - name: Ensure .ssh directory exists for ubuntu user
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Find all public keys in keys/ directory
      local_action:
        module: find
        paths: "{{ playbook_dir }}/keys"
        patterns: "*.pub"
      register: public_keys
      become: no

    - name: Deploy public keys to authorized_keys
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ public_keys.files }}"
      when: public_keys.files | length > 0

  handlers:
    - name: Restart SSH
      systemd:
        name: sshd
        state: restarted
