---
- name: Test Connection Servers
  hosts: all
  gather_facts: no

  tasks:
    - name: Test ping connectivity
      ping:
      register: ping_result

    - name: Display ping result
      debug:
        msg: "✓ Successfully connected to {{ inventory_hostname }}"

    - name: Gather basic system facts
      setup:
        gather_subset:
          - '!all'
          - 'min'
      register: facts

    - name: Display system information
      debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "OS Family: {{ ansible_os_family }}"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Python: {{ ansible_python_version }}"

    - name: Check current user
      command: whoami
      register: current_user
      changed_when: false

    - name: Display current user
      debug:
        msg: "Connected as user: {{ current_user.stdout }}"
