---
- name: Deploy SSH Keys to Ubuntu Server
  hosts: ubuntu_servers
  become: yes
  gather_facts: yes

  tasks:
    # ============================================
    # Ensure ubuntu user exists
    # ============================================
    - name: Ensure ubuntu user exists
      user:
        name: ubuntu
        state: present

    # ============================================
    # Configure SSH directory
    # ============================================
    - name: Ensure .ssh directory exists for ubuntu user
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    # ============================================
    # Deploy SSH public keys
    # ============================================
    - name: Find all public keys in keys/ directory
      find:
        paths: "{{ playbook_dir }}/keys"
        patterns: "*.pub"
      register: public_keys
      delegate_to: localhost
      become: no

    - name: Deploy public keys to authorized_keys
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ public_keys.files }}"
      when: public_keys.files | length > 0
